name: CI
on:
  push:
    branches:
    - mill-build
  pull_request:

jobs:
  compile-all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6
    - uses: coursier/setup-action@v1
      with:
        jvm: 17
    - name: Setup Mill
      run: .github/scripts/setup-dev-mill.sh
    - name: Compile everything
      run: ./mill -i __.compile

  hybrid-bootstrapping-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6
    - uses: coursier/setup-action@v1
      with:
        jvm: 17
    - name: Setup Mill
      run: .github/scripts/setup-dev-mill.sh
    - name: Test
      run: ./mill -i __.hybrid.bootstrapping.test

  hybrid-final-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6
    - uses: coursier/setup-action@v1
      with:
        jvm: 17
    - name: Setup Mill
      run: .github/scripts/setup-dev-mill.sh
    - name: Test
      run: ./mill -i __.hybrid.final.test

  pure-bootstrapping-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6
    - uses: coursier/setup-action@v1
      with:
        jvm: 17
    - name: Setup Mill
      run: .github/scripts/setup-dev-mill.sh
    - name: Test
      run: ./mill -i __.pure.bootstrapping.test

  pure-final-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6
    - uses: coursier/setup-action@v1
      with:
        jvm: 17
    - name: Setup Mill
      run: .github/scripts/setup-dev-mill.sh
    - name: Test
      run: ./mill -i __.pure.final.test
