name: CI
on:
  push:
    branches:
    - mill-build
  pull_request:

jobs:
  compile-all:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6
    - uses: coursier/setup-action@v1
      with:
        jvm: 17
    - name: Setup Mill
      run: .github/scripts/setup-dev-mill.sh
    - name: No modules with empty sources
      run: ./mill -i ci.noEmptySources --tasks __.allSourceFiles
    - name: Compile everything
      run: ./mill -i __.compile

  tests:
    runs-on: ubuntu-latest
    name: ${{ matrix.KIND }}-${{ matrix.LEVEL }}-${{ matrix.TEST }}
    strategy:
      fail-fast: false
      matrix:
        KIND: ["hybrid", "pure"]
        LEVEL: ["bootstrapping", "final"]
        TEST: ["test", "munit"]
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        # submodules: true
    - uses: coursier/cache-action@v6
    - uses: coursier/setup-action@v1
      with:
        jvm: 17
    - name: Setup Mill
      run: .github/scripts/setup-dev-mill.sh
    - name: Test
      run: ./mill -i '__[${{ matrix.KIND }},${{ matrix.LEVEL }}].${{ matrix.TEST }}'
